client:
  pseudo:
    property: Property value loaded from Git System new updated by Uday
    property1: Property value loaded from Git System new updated11 by Sathish uday
    property2: Property value loaded from Git System new updated22
